name: rqdq-hello
version: "2.12"
summary: NET Hello, the "hello world" snap
description: .NET Hello prints a friendly greeting.
grade: stable
confinement: strict
architectures: 
  - armhf

apps:
  hello:
    command: publish/hello

parts:
  net-hello:
    plugin: dump
    source: src/bin
    stage-packages:
      - libunwind8
      - libicu55
      - icu-devtools
      - libc6
      - libcurl3
      - libgcc1
      - libgssapi-krb5-2
      - libicu-dev
      - liblttng-ust0
      - libstdc++6
      - libunwind8
      - libuuid1
      - wget
      - zlib1g


